### ISSUE TITLE
check panics on example 01 with JSON output

### ISSUE THREAD

**Issue by dnaka91** [EmbarkStudios/cargo-deny#378]
**Describe the bug**
When running cargo-deny with `-f json` on the `01_allow_license` in this repository, the application panics.

The exact error I get is:
```txt
thread '<unnamed>' panicked at 'byte index 44 is out of bounds of `[licenses]
allow = [ "MIT" ]
`', /Users/***/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-deny-0.10.2/src/diag/obj_grapher.rs:150:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::str::slice_error_fail
   3: cargo_deny::diag::obj_grapher::cs_diag_to_json
   4: cargo_deny::diag::obj_grapher::diag_to_json
   5: cargo_deny::common::OutputLock::print_krate_diag
   6: cargo_deny::check::print_diagnostics
   7: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
   8: rayon_core::registry::WorkerThread::wait_until_cold
   9: rayon_core::registry::ThreadBuilder::run
```

**To Reproduce**
1. Install latest cargo-deny (`cargo install cargo-deny`).
2. Clone the cargo-deny repository.
3. Go to the `examples/01_allow_license` subfolder.
4. Run cargo-deny with JSON output (`cargo deny -f json check`)
5. cargo-deny panics with an out of bounds error

**Expected behavior**
cargo-deny shouldn't panic and instead produce the expected JSON output.

**Device:**
 - OS: MacOS
 - Version: 11.6.1

**Comment by dnaka91** [comment]
Thanks for the quick fix 🚀
