### ISSUE TITLE
Mac test failures

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#4]
Tested building and running the tests with the latest on my Mac and ran into the following test failures:

```sh
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/cargo_deny-03df1ab5b72f57fa

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/license_gather-383da906ad794640

running 13 tests
test handles_exception_in_metadata ... ok
test handles_multiple_spdx_id_in_metadata ... ok
test handles_spdx_id_in_metadata ... ok
test detects_unlicensed ... ok
test handles_unknown_spdx_id_in_metadata ... ok
test handles_multiple_unknown_spdx_ids_in_metadata ... ok
test analyzes_license_file ... FAILED
test analyzes_inferred_license_file ... FAILED
test handles_unknown_explicit ... FAILED
test ignores_explicit ... FAILED
test ignores_implicit ... FAILED
test analyzes_multiple_inferred_license_files ... FAILED
test analyzes_explicit_and_inferred_license_files ... FAILED

failures:

---- analyzes_license_file stdout ----
thread 'analyzes_license_file' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21

---- analyzes_inferred_license_file stdout ----
thread 'analyzes_inferred_license_file' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "cache version mismatch" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- handles_unknown_explicit stdout ----
thread 'handles_unknown_explicit' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21

---- ignores_explicit stdout ----
thread 'ignores_explicit' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21

---- ignores_implicit stdout ----
thread 'ignores_implicit' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21

---- analyzes_multiple_inferred_license_files stdout ----
thread 'analyzes_multiple_inferred_license_files' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21

---- analyzes_explicit_and_inferred_license_files stdout ----
thread 'analyzes_explicit_and_inferred_license_files' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21


failures:
    analyzes_explicit_and_inferred_license_files
    analyzes_inferred_license_file
    analyzes_license_file
    analyzes_multiple_inferred_license_files
    handles_unknown_explicit
    ignores_explicit
    ignores_implicit
```

**Comment by Jake-Shadle** [comment]
Ahh wait, this is probably because you don't have git lfs installed, and the spdx-cache.bin.zstd file in the root is just the sha1 of the content.

**Comment by repi** [comment]
Yup that was it, installed Git LFS and re-cloned the repo (maybe not needed), and now it works.

Should add it to the README though that it is required.

**Comment by Jake-Shadle** [comment]
Yup, added a note about that in 40d1a9ec1feff4761b8de1cb813fe94dba71e556.
