### ISSUE TITLE
Test failure in the last release

### ISSUE THREAD

**Issue by orhun** [EmbarkStudios/cargo-deny#540]
**Describe the bug**

Hey, Arch packager of `cargo-deny` here 👋🏼 

I came across this test failure for the latest release (`0.14.0`):

```
test downgrades_lint_levels ... ok
test detects_vulnerabilities ... ok
test detects_unsound ... ok
test warns_on_ignored_and_withdrawn ... ok
test detects_unmaintained ... ok
test warns_on_index_failures ... ok

failures:

---- detects_yanked stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/snapshots/advisories__detects_yanked.snap
Snapshot: detects_yanked
Source: tests/advisories.rs:217
────────────────────────────────────────────────────────────────────────────────
Expression: diags
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
   28    28 │       "message": "detected yanked crate (try `cargo update -p crate-two`)",
   29    29 │       "severity": "error"
   30    30 │     },
   31    31 │     "type": "diagnostic"
   32       │-  },
   33       │-  {
   34       │-    "fields": {
   35       │-      "code": "yanked",
   36       │-      "graphs": [
   37       │-        {
   38       │-          "Krate": {
   39       │-            "name": "spdx",
   40       │-            "version": "0.3.1"
   41       │-          },
   42       │-          "parents": [
   43       │-            {
   44       │-              "Krate": {
   45       │-                "name": "yank-check",
   46       │-                "version": "0.1.0"
   47       │-              }
   48       │-            }
   49       │-          ]
   50       │-        }
   51       │-      ],
   52       │-      "labels": [
   53       │-        {
   54       │-          "column": 1,
   55       │-          "line": 7,
   56       │-          "message": "yanked version",
   57       │-          "span": "spdx 0.3.1 registry+https://github.com/rust-lang/crates.io-index"
   58       │-        }
   59       │-      ],
   60       │-      "message": "detected yanked crate (try `cargo update -p spdx`)",
   61       │-      "severity": "error"
   62       │-    },
   63       │-    "type": "diagnostic"
   64    32 │   }
   65    33 │ ]
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'detects_yanked' panicked at 'snapshot assertion for 'detects_yanked' failed in line 217', /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.31.0/src/runtime.rs:563:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    detects_yanked

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.39s

error: test failed, to rerun pass `--test advisories`
```

**To Reproduce**
1. Use the `PKGBUILD` from [Arch Linux repos](https://gitlab.archlinux.org/archlinux/packaging/packages/cargo-deny).
2. Remove `--skip "detects_yanked"` from `cargo test` command.
3. Build in a clean chroot [*](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot). 

**Expected behavior**
Successful build.

**Screenshots**
\-

**Device:**
 - OS: Arch Linux
 - Version `0.4.0`

**Additional context**

See the packaging changes here: https://gitlab.archlinux.org/archlinux/packaging/packages/cargo-deny/-/commit/22991cfa2de301aa2289066b4281c8d2410d9d38

**Comment by Jake-Shadle** [comment]
So that output indicates the "old" snapshot is from the current 0.14 version, which you can tell because of the "(try `cargo update -p spdx`)" which was added in https://github.com/EmbarkStudios/cargo-deny/commit/bf2120797e1a56855b1cdf420dce97625c4045b3, so feels like maybe you ran the check once, updated the snapshot, and then downgraded to an older version? Or something? No idea, but the snapshot in the repo is correct.

**Comment by Jake-Shadle** [comment]
So the snapshot is correct, that should be the output, is there something that would prevent files being written to disk inside target/tmp and/or restrict network access?

**Comment by orhun** [comment]
I am not sure, we're building packages in chroot but that shouldn't be a problem. (cc @freswa)

**Comment by freswa** [comment]
We're building in a systemd-nspawn container. There are limits to syscalls, but everything else should work as expected.

**Comment by Jake-Shadle** [comment]
Ok, well, I'll get around to fixing this unless someone more familiar with the packaging makes a PR, but it will be low priority for me as the test is working properly for this projects CI, which is what I care about most.

**Comment by icp1994** [comment]
If it's of any help, I got the same failure while updating in Void but only for [i686](https://github.com/void-linux/void-packages/actions/runs/5829958568/job/15810398198?pr=45529). It passed fine as is for [amd64](https://github.com/void-linux/void-packages/actions/runs/5829958568/job/15810398081?pr=45529#step:7:881).

**Comment by orhun** [comment]
It seems like this is fixed with the last release. https://gitlab.archlinux.org/archlinux/packaging/packages/cargo-deny/-/commit/02d98ce232dd9d0d7412d0015acc1d8c0a14d587

**Comment by kpcyrd** [comment]
I'm still having two test failures on Alpine, but only on these architectures:

- armhf
- armv7
- s390x
- x86

The tests pass on the following:

- aarch64
- ppc64le
- riscv64
- x86_64

I'm suspecting this is related to 32 vs 64 bits.

![image](https://github.com/user-attachments/assets/a0a96cc9-a9ea-4984-9fb9-16c1273acf91)

https://gitlab.alpinelinux.org/kpcyrd/aports/-/pipelines/250843

The two test failures are always:

```
running 4 tests
test clones_with_gix ... ok
test clones_with_git ... ok
test crates_io_source_replacement ... FAILED
test detects_yanked ... FAILED
failures:
---- crates_io_source_replacement stdout ----
thread 'crates_io_source_replacement' panicked at tests/advisories.rs:597:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- detects_yanked stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/snapshots/advisories__detects_yanked.snap
Snapshot: detects_yanked
Source: tests/advisories.rs:237
────────────────────────────────────────────────────────────────────────────────
Expression: diags
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0       │-[
    1       │-  {
    2       │-    "fields": {
    3       │-      "code": "yanked",
    4       │-      "graphs": [
    5       │-        {
    6       │-          "Krate": {
    7       │-            "name": "crate-two",
    8       │-            "version": "0.1.0"
    9       │-          },
   10       │-          "parents": [
   11       │-            {
   12       │-              "Krate": {
   13       │-                "name": "yank-check",
   14       │-                "version": "0.1.0"
   15       │-              }
   16       │-            }
   17       │-          ]
   18       │-        }
   19       │-      ],
   20       │-      "labels": [
   21       │-        {
   22       │-          "column": 1,
   23       │-          "line": 2,
   24       │-          "message": "yanked version",
   25       │-          "span": "crate-two 0.1.0 registry+https://github.com/EmbarkStudios/cargo-test-index"
   26       │-        }
   27       │-      ],
   28       │-      "message": "detected yanked crate (try `cargo update -p crate-two`)",
   29       │-      "severity": "error"
   30       │-    },
   31       │-    "type": "diagnostic"
   32       │-  },
   33       │-  {
   34       │-    "fields": {
   35       │-      "code": "yanked",
   36       │-      "graphs": [
   37       │-        {
   38       │-          "Krate": {
   39       │-            "name": "spdx",
   40       │-            "version": "0.3.1"
   41       │-          },
   42       │-          "parents": [
   43       │-            {
   44       │-              "Krate": {
   45       │-                "name": "yank-check",
   46       │-                "version": "0.1.0"
   47       │-              }
   48       │-            }
   49       │-          ]
   50       │-        }
   51       │-      ],
   52       │-      "labels": [
   53       │-        {
   54       │-          "column": 1,
   55       │-          "line": 7,
   56       │-          "message": "yanked version",
   57       │-          "span": "spdx 0.3.1 registry+https://github.com/rust-lang/crates.io-index"
   58       │-        }
   59       │-      ],
   60       │-      "message": "detected yanked crate (try `cargo update -p spdx`)",
   61       │-      "severity": "error"
   62       │-    },
   63       │-    "type": "diagnostic"
   64       │-  }
   65       │-]
          0 │+[]
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'detects_yanked' panicked at /home/buildozer/.cargo/registry/src/index.crates.io-1cd66030c949c28d/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'detects_yanked' failed in line 237
failures:
    crates_io_source_replacement
    detects_yanked
test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 9 filtered out; finished in 1.65s
error: test failed, to rerun pass `--test advisories`
```

**Comment by paolobarbolini** [comment]
This still fails on v0.16.3 on i686, armv7 and armhf.

```
failures:
---- test::validate_crates_io_sparse_dir_name stdout ----
thread 'test::validate_crates_io_sparse_dir_name' panicked at src/lib.rs:671:9:
assertion `left == right` failed
  left: "index.crates.io-1cd66030c949c28d"
 right: "index.crates.io-6f17d22bba15001f"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    test::validate_crates_io_sparse_dir_name
test result: FAILED. 13 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
```
